import { Inter } from "next/font/google";
import "./globals.css";
import { ConfigProvider } from "antd";
import { AuthProvider } from "@/context/authprovider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html>
      <body>
        <ConfigProvider
          theme={{
            token: {
              colorPrimary: "linear-gradient(135deg, #FF1493, #800080)",
            },
            components: {
              Button: {
                colorPrimary: "linear-gradient(135deg, #FF1493, #800080)",
              },
            },
          }}
        >
          <AuthProvider>{children}</AuthProvider>
        </ConfigProvider>
      </body>
    </html>
  );
}
